
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '1C4CFF14EDDDDDEB36CBB25F935A638A'
    
_lr_action_items = {'AND':([1,2,5,7,8,9,15,16,17,18,19,],[-7,-9,10,10,-5,-4,-6,-3,10,10,-8,]),'IMPLIES':([1,2,5,7,8,9,15,16,17,18,19,],[-7,-9,11,11,-5,-4,-6,-3,11,-2,-8,]),'OR':([1,2,5,7,8,9,15,16,17,18,19,],[-7,-9,12,12,-5,-4,-6,-3,12,-2,-8,]),'COMMA':([2,14,19,],[-9,20,-8,]),'LPAREN':([0,2,3,4,10,11,12,],[3,6,3,3,3,3,3,]),'NOT':([0,3,4,10,11,12,],[4,4,4,4,4,4,]),'RPAREN':([1,2,7,8,9,13,14,15,16,17,18,19,21,],[-7,-9,15,-5,-4,19,-11,-6,-3,-1,-2,-8,-10,]),'ID':([0,3,4,6,10,11,12,20,],[2,2,2,2,2,2,2,2,]),'$end':([1,2,5,8,9,15,16,17,18,19,],[-7,-9,0,-5,-4,-6,-3,-1,-2,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'FORMULA':([0,3,4,10,11,12,],[5,7,9,16,17,18,]),'TERM':([0,3,4,6,10,11,12,20,],[1,1,8,14,1,1,1,14,]),'TERMLIST':([6,20,],[13,21,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> FORMULA","S'",1,None,None,None),
  ('FORMULA -> FORMULA IMPLIES FORMULA','FORMULA',3,'p_formula_binary','Resolution.py',44),
  ('FORMULA -> FORMULA OR FORMULA','FORMULA',3,'p_formula_binary','Resolution.py',45),
  ('FORMULA -> FORMULA AND FORMULA','FORMULA',3,'p_formula_binary','Resolution.py',46),
  ('FORMULA -> NOT FORMULA','FORMULA',2,'p_formula_not','Resolution.py',52),
  ('FORMULA -> NOT TERM','FORMULA',2,'p_formula_not','Resolution.py',53),
  ('FORMULA -> LPAREN FORMULA RPAREN','FORMULA',3,'p_formula_group','Resolution.py',58),
  ('FORMULA -> TERM','FORMULA',1,'p_formula_ID','Resolution.py',63),
  ('TERM -> ID LPAREN TERMLIST RPAREN','TERM',4,'p_term','Resolution.py',67),
  ('TERM -> ID','TERM',1,'p_term','Resolution.py',68),
  ('TERMLIST -> TERM COMMA TERMLIST','TERMLIST',3,'p_termlist','Resolution.py',73),
  ('TERMLIST -> TERM','TERMLIST',1,'p_termlist','Resolution.py',74),
]
